from starlette.routing import Route

from .endpoints_account import (
    change_password,
    change_profile,
    create_account,
    login,
    logout,
    mfa_authenticate,
    mfa_status,
    reset_password,
    set_password,
    totp_register,
    totp_remove,
    webauthn_register,
    webauthn_remove,
    webauthn_verify_authentication_response,
    webauthn_verify_registration_response,
)
from .endpoints_mntners import (
    mntner_migrate_complete,
    mntner_migrate_initiate,
    permission_add,
    permission_delete,
)
from .http_endpoints import (
    index,
    maintained_objects,
    rpsl_detail,
    rpsl_update,
    user_detail,
)

UI_ROUTES = [
    Route("/", index, name="index"),
    Route("/maintained-objects/", maintained_objects, name="maintained_objects"),
    Route(
        "/rpsl/update/{source}/{object_class}/{rpsl_pk:path}",
        rpsl_update,
        name="rpsl_update",
        methods=["GET", "POST"],
    ),
    Route("/rpsl/update/", rpsl_update, name="rpsl_update", methods=["GET", "POST"]),
    Route("/rpsl/{source}/{object_class}/{rpsl_pk:path}", rpsl_detail, name="rpsl_detail"),
    Route(
        "/migrate-mntner/",
        mntner_migrate_initiate,
        name="mntner_migrate_initiate",
        methods=["GET", "POST"],
    ),
    Route(
        "/migrate-mntner/complete/{pk:uuid}/{token}",
        mntner_migrate_complete,
        name="mntner_migrate_complete",
        methods=["GET", "POST"],
    ),
    Route("/user", user_detail, name="user_detail"),
    Route(
        "/permission/add/{mntner:uuid}",
        permission_add,
        name="permission_add",
        methods=["GET", "POST"],
    ),
    Route(
        "/permission/delete/{permission:uuid}",
        permission_delete,
        name="permission_delete",
        methods=["GET", "POST"],
    ),
    Route("/accounts/create/", create_account, name="create_account", methods=["GET", "POST"]),
    Route(
        "/accounts/set-password/{pk}/{token}/{initial:int}",
        set_password,
        name="set_password",
        methods=["GET", "POST"],
    ),
    Route("/accounts/reset-password/", reset_password, name="reset_password", methods=["GET", "POST"]),
    Route("/accounts/change-password/", change_password, name="change_password", methods=["GET", "POST"]),
    Route("/accounts/change-profile/", change_profile, name="change_profile", methods=["GET", "POST"]),
    Route("/accounts/mfa-status/", mfa_status, name="mfa_status"),
    Route("/accounts/totp-register/", totp_register, name="totp_register", methods=["GET", "POST"]),
    Route("/accounts/totp-remove/", totp_remove, name="totp_remove", methods=["GET", "POST"]),
    Route(
        "/accounts/webauthn-remove/{webauthn:uuid}",
        webauthn_remove,
        name="webauthn_remove",
        methods=["GET", "POST"],
    ),
    Route("/accounts/webauthn-register/", webauthn_register, name="webauthn_register"),
    Route(
        "/accounts/webauthn-verify-registration-response/",
        webauthn_verify_registration_response,
        name="webauthn_verify_registration_response",
        methods=["POST"],
    ),
    Route("/accounts/mfa-authenticate/", mfa_authenticate, name="mfa_authenticate", methods=["GET", "POST"]),
    Route(
        "/accounts/webauthn-verify-authentication-response/",
        webauthn_verify_authentication_response,
        name="webauthn_verify_authentication_response",
        methods=["POST"],
    ),
    Route("/login/", login, name="login", methods=["GET", "POST"]),
    Route("/logout/", logout, name="logout"),
]
